// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_dut.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_dut
// Source Path: dvfs_core_ip/dvfs_core_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_dut
          (clk,
           reset,
           dut_enable,
           u,
           ce_out,
           p_state,
           W_log);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   [63:0] u;  // ufix64
  output  ce_out;  // ufix1
  output  [7:0] p_state;  // ufix8
  output  [63:0] W_log;  // ufix64


  wire enb;
  wire ce_out_sig;  // ufix1
  wire [7:0] p_state_sig;  // ufix8
  wire [63:0] W_log_sig;  // ufix64


  assign enb = dut_enable;

  dvfs_core_ip_src_dvfs_core_hdl u_dvfs_core_ip_src_dvfs_core_hdl (.clk(clk),
                                                                   .clk_enable(enb),
                                                                   .reset(reset),
                                                                   .u(u),  // ufix64
                                                                   .ce_out(ce_out_sig),  // ufix1
                                                                   .p_state(p_state_sig),  // ufix8
                                                                   .W_log(W_log_sig)  // ufix64
                                                                   );

  assign ce_out = ce_out_sig;

  assign p_state = p_state_sig;

  assign W_log = W_log_sig;

endmodule  // dvfs_core_ip_dut

