// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_addr_decoder_read.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_addr_decoder_read
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_addr_decoder/dvfs_core_ip_addr_decoder_read
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_addr_decoder_read
          (IPCORE_CLK,
           IPCORE_RESET,
           AXI4_ACLK,
           AXI4_ARESET,
           addr_read,
           rd_enb,
           read_axi_enable_sync,
           read_ip_timestamp,
           read_u_sync,
           read_p_state,
           read_W_log_strobe,
           read_W_log,
           rd_enb_ack,
           s_data_read);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESET;  // ufix1
  input   AXI4_ACLK;
  input   AXI4_ARESET;
  input   [13:0] addr_read;  // ufix14
  input   rd_enb;  // ufix1
  input   read_axi_enable_sync;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   [63:0] read_u_sync;  // ufix64
  input   [7:0] read_p_state;  // ufix8
  input   read_W_log_strobe;  // ufix1
  input   [63:0] read_W_log;  // ufix64
  output  rd_enb_ack;  // ufix1
  output  [31:0] s_data_read;  // ufix32


  wire enb;
  wire s_decoder_rd_enb_latch;  // ufix1
  wire const_1;  // ufix1
  wire [6:0] address_select_level1;  // ufix7
  (* cdc_info  = "max_delay_endpoint_ip_to_axi", dont_touch  = "true" *)   reg readback_reg_axi_enable;  // ufix1
  wire [31:0] data_slice_axi_enable_1;  // ufix32
  wire [31:0] read_ip_timestamp_sync;  // ufix32
  wire [7:0] read_p_state_sync;  // ufix8
  wire [63:0] read_W_log_sync;  // ufix64
  (* cdc_info  = "max_delay_endpoint_ip_to_axi", dont_touch  = "true" *)   reg [31:0] read_reg_ip_timestamp;  // ufix32
  (* cdc_info  = "max_delay_endpoint_ip_to_axi", dont_touch  = "true" *)   reg [63:0] readback_reg_u;  // ufix64
  wire [31:0] read_reg_slice_u_1;  // ufix32
  wire [31:0] read_reg_slice_u_2;  // ufix32
  (* cdc_info  = "max_delay_endpoint_ip_to_axi", dont_touch  = "true" *)   reg [7:0] read_reg_p_state;  // ufix8
  wire [31:0] data_slice_p_state_1;  // ufix32
  (* cdc_info  = "max_delay_endpoint_ip_to_axi", dont_touch  = "true" *)   reg [63:0] sync_reg_W_log;  // ufix64
  wire [31:0] read_reg_slice_W_log_1;  // ufix32
  wire [31:0] read_reg_slice_W_log_2;  // ufix32
  wire [31:0] const_0;  // ufix32
  reg [31:0] mux_out0_level1;  // ufix32


  dvfs_core_ip_pulse_sync u_dvfs_core_ip_rd_enable_sync_inst (.i_send_clk(AXI4_ACLK),
                                                              .i_send_rst(AXI4_ARESET),
                                                              .i_receive_clk(IPCORE_CLK),  // ufix1
                                                              .i_receive_rst(IPCORE_RESET),  // ufix1
                                                              .i_send_pulse(rd_enb),  // ufix1
                                                              .o_receive_pulse(s_decoder_rd_enb_latch),  // ufix1
                                                              .o_pulse_ack(rd_enb_ack)  // ufix1
                                                              );

  assign const_1 = 1'b1;

  assign enb = const_1;

  assign address_select_level1 = addr_read[6:0];

  always @(posedge AXI4_ACLK)
    begin : reg_sync_axi_enable_process
      if (AXI4_ARESET == 1'b1) begin
        readback_reg_axi_enable <= 1'b0;
      end
      else begin
        if (enb && rd_enb_ack) begin
          readback_reg_axi_enable <= read_axi_enable_sync;
        end
      end
    end

  assign data_slice_axi_enable_1 = {31'b0, readback_reg_axi_enable};

  dvfs_core_ip_addr_decoder_read_registers u_dvfs_core_ip_addr_decoder_read_registers_inst (.IPCORE_CLK(IPCORE_CLK),  // ufix1
                                                                                            .IPCORE_RESET(IPCORE_RESET),  // ufix1
                                                                                            .rd_enb_latch(s_decoder_rd_enb_latch),  // ufix1
                                                                                            .read_ip_timestamp(read_ip_timestamp),  // ufix32
                                                                                            .read_p_state(read_p_state),  // ufix8
                                                                                            .read_W_log_strobe(read_W_log_strobe),  // ufix1
                                                                                            .read_W_log(read_W_log),  // ufix64
                                                                                            .read_ip_timestamp_sync(read_ip_timestamp_sync),  // ufix32
                                                                                            .read_p_state_sync(read_p_state_sync),  // ufix8
                                                                                            .read_W_log_sync(read_W_log_sync)  // ufix64
                                                                                            );

  always @(posedge AXI4_ACLK)
    begin : reg_sync_ip_timestamp_process
      if (AXI4_ARESET == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && rd_enb_ack) begin
          read_reg_ip_timestamp <= read_ip_timestamp_sync;
        end
      end
    end

  always @(posedge AXI4_ACLK)
    begin : reg_sync_u_process
      if (AXI4_ARESET == 1'b1) begin
        readback_reg_u <= 64'h0000000000000000;
      end
      else begin
        if (enb && rd_enb_ack) begin
          readback_reg_u <= read_u_sync;
        end
      end
    end

  assign read_reg_slice_u_1 = readback_reg_u[31:0];

  assign read_reg_slice_u_2 = readback_reg_u[63:32];

  always @(posedge AXI4_ACLK)
    begin : reg_sync_p_state_process
      if (AXI4_ARESET == 1'b1) begin
        read_reg_p_state <= 8'b00000000;
      end
      else begin
        if (enb && rd_enb_ack) begin
          read_reg_p_state <= read_p_state_sync;
        end
      end
    end

  assign data_slice_p_state_1 = {24'b0, read_reg_p_state};

  always @(posedge AXI4_ACLK)
    begin : reg_sync_W_log_process
      if (AXI4_ARESET == 1'b1) begin
        sync_reg_W_log <= 64'h0000000000000000;
      end
      else begin
        if (enb && rd_enb_ack) begin
          sync_reg_W_log <= read_W_log_sync;
        end
      end
    end

  assign read_reg_slice_W_log_1 = sync_reg_W_log[31:0];

  assign read_reg_slice_W_log_2 = sync_reg_W_log[63:32];

  assign const_0 = 32'b00000000000000000000000000000000;

  always @(address_select_level1, const_0, data_slice_axi_enable_1, data_slice_p_state_1,
       read_reg_ip_timestamp, read_reg_slice_W_log_1, read_reg_slice_W_log_2,
       read_reg_slice_u_1, read_reg_slice_u_2) begin
    case ( address_select_level1)
      7'b0000001 :
        begin
          mux_out0_level1 = data_slice_axi_enable_1;
        end
      7'b0000010 :
        begin
          mux_out0_level1 = read_reg_ip_timestamp;
        end
      7'b1000000 :
        begin
          mux_out0_level1 = read_reg_slice_u_1;
        end
      7'b1000001 :
        begin
          mux_out0_level1 = read_reg_slice_u_2;
        end
      7'b1000011 :
        begin
          mux_out0_level1 = data_slice_p_state_1;
        end
      7'b1000100 :
        begin
          mux_out0_level1 = read_reg_slice_W_log_1;
        end
      7'b1000101 :
        begin
          mux_out0_level1 = read_reg_slice_W_log_2;
        end
      default :
        begin
          mux_out0_level1 = const_0;
        end
    endcase
  end

  assign s_data_read = mux_out0_level1;

endmodule  // dvfs_core_ip_addr_decoder_read

