// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_addr_decoder_write.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_addr_decoder_write
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_addr_decoder/dvfs_core_ip_addr_decoder_write
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_addr_decoder_write
          (IPCORE_CLK,
           IPCORE_GLOBAL_RESET,
           data_write,
           addr_write,
           wr_enb,
           read_axi_enable_sync,
           write_axi_enable,
           read_u_sync,
           write_u,
           read_W_log_strobe);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_GLOBAL_RESET;  // ufix1
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_write;  // ufix14
  input   wr_enb;  // ufix1
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output read_axi_enable_sync;  // ufix1
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output write_axi_enable;  // ufix1
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output [63:0] read_u_sync;  // ufix64
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output [63:0] write_u;  // ufix64
  output  read_W_log_strobe;  // ufix1


  wire enb;
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  wire const_1;  // ufix1
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)   reg data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_u;  // ufix1
  wire strobe_sel_u;  // ufix1
  wire const_zero;  // ufix1
  wire strobe_in_u;  // ufix1
  wire strobe_sw_u;  // ufix1
  wire decode_sel_u_1_2;  // ufix1
  wire reg_enb_u_1_2;  // ufix1
  reg [31:0] data_reg_u_1_2;  // ufix32
  wire decode_sel_u_1_1;  // ufix1
  wire reg_enb_u_1_1;  // ufix1
  reg  strobe_reg_u;  // ufix1
  reg [31:0] data_reg_u_1_1;  // ufix32
  wire [63:0] data_concat_u_1;  // ufix64
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)   reg [63:0] sync_reg_u_1;  // ufix64
  wire decode_sel_W_log;  // ufix1
  wire strobe_sel_W_log;  // ufix1
  wire const_zero_1;  // ufix1
  wire strobe_in_W_log;  // ufix1
  wire strobe_sw_W_log;  // ufix1
  reg  strobe_reg_W_log;  // ufix1


  assign decode_sel_axi_enable_1_1 = addr_write == 14'b00000000000001;

  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;

  assign data_in_axi_enable = data_write[0];

  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge IPCORE_CLK)
    begin : reg_axi_enable_1_1_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end

  assign read_axi_enable_sync = data_reg_axi_enable_1_1;

  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_u = addr_write == 14'b00000001000010;

  assign strobe_sel_u = decode_sel_u & wr_enb;

  assign const_zero = 1'b0;

  assign strobe_in_u = data_write[0];

  assign strobe_sw_u = (strobe_sel_u == 1'b0 ? const_zero :
              strobe_in_u);

  assign decode_sel_u_1_2 = addr_write == 14'b00000001000001;

  assign reg_enb_u_1_2 = decode_sel_u_1_2 & wr_enb;

  always @(posedge IPCORE_CLK)
    begin : reg_u_1_2_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        data_reg_u_1_2 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && reg_enb_u_1_2) begin
          data_reg_u_1_2 <= data_write;
        end
      end
    end

  assign decode_sel_u_1_1 = addr_write == 14'b00000001000000;

  assign reg_enb_u_1_1 = decode_sel_u_1_1 & wr_enb;

  always @(posedge IPCORE_CLK)
    begin : reg_rsvd_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        strobe_reg_u <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_u <= strobe_sw_u;
        end
      end
    end

  always @(posedge IPCORE_CLK)
    begin : reg_u_1_1_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        data_reg_u_1_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && reg_enb_u_1_1) begin
          data_reg_u_1_1 <= data_write;
        end
      end
    end

  assign data_concat_u_1 = {data_reg_u_1_2, data_reg_u_1_1};

  always @(posedge IPCORE_CLK)
    begin : sync_reg_u_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        sync_reg_u_1 <= 64'h0000000000000000;
      end
      else begin
        if (enb && strobe_reg_u) begin
          sync_reg_u_1 <= data_concat_u_1;
        end
      end
    end

  assign read_u_sync = sync_reg_u_1;

  assign write_u = sync_reg_u_1;

  assign decode_sel_W_log = addr_write == 14'b00000001000110;

  assign strobe_sel_W_log = decode_sel_W_log & wr_enb;

  assign const_zero_1 = 1'b0;

  assign strobe_in_W_log = data_write[0];

  assign strobe_sw_W_log = (strobe_sel_W_log == 1'b0 ? const_zero_1 :
              strobe_in_W_log);

  always @(posedge IPCORE_CLK)
    begin : reg_rsvd_1_process
      if (IPCORE_GLOBAL_RESET == 1'b1) begin
        strobe_reg_W_log <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_W_log <= strobe_sw_W_log;
        end
      end
    end

  assign read_W_log_strobe = strobe_reg_W_log;

endmodule  // dvfs_core_ip_addr_decoder_write

