# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dvfs_bd/dvfs_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvfs_bd || ORIG_REF_NAME==dvfs_bd} -quiet] -quiet

# IP: bd/dvfs_bd/ip/dvfs_bd_processing_system7_0_0/dvfs_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvfs_bd_processing_system7_0_0 || ORIG_REF_NAME==dvfs_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/dvfs_bd/ip/dvfs_bd_dvfs_core_ip_0_0/dvfs_bd_dvfs_core_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvfs_bd_dvfs_core_ip_0_0 || ORIG_REF_NAME==dvfs_bd_dvfs_core_ip_0_0} -quiet] -quiet

# IP: bd/dvfs_bd/ip/dvfs_bd_axi_smc_0/dvfs_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvfs_bd_axi_smc_0 || ORIG_REF_NAME==dvfs_bd_axi_smc_0} -quiet] -quiet

# IP: bd/dvfs_bd/ip/dvfs_bd_rst_ps7_0_100M_0/dvfs_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dvfs_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==dvfs_bd_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/projects/dvfs_zed/dvfs_zed_project/dvfs_zed_project.gen/sources_1/bd/dvfs_bd/dvfs_bd_ooc.xdc
