function gs_dvfs_zed_simple_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 25.2 (R2025b) at 11:46:22 on 20/11/2025.
% This function was created for the IP Core generated from design 'dvfs_zed_simple'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x400D0000, ...
	"AddressRange", 0x10000, ...
	"WriteDeviceName", "mwipcore0:mmwr0", ...
	"ReadDeviceName", "mwipcore0:mmrd0");

DUTPort_u = hdlcoder.DUTPort("u", ...
	"Direction", "INOUT", ...
	"DataType", "double", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_p_state = hdlcoder.DUTPort("p_state", ...
	"Direction", "OUT", ...
	"DataType", "uint8", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x10C");

DUTPort_W_log = hdlcoder.DUTPort("W_log", ...
	"Direction", "OUT", ...
	"DataType", "double", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x110");

mapPort(hFPGA, [DUTPort_u, DUTPort_p_state, DUTPort_W_log]);

end
