// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_write_sync_receive_clk.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_write_sync_receive_clk
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_axi_lite_module/dvfs_core_ip_write_data_sync/dvfs_core_ip_write_sync_receive_clk
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_write_sync_receive_clk
          (i_receive_clk,
           i_receive_rst,
           i_level_send,
           i_send_data,
           i_send_address,
           o_receive_pulse,
           o_level_receive,
           o_receive_data,
           o_receive_address);


  input   i_receive_clk;  // ufix1
  input   i_receive_rst;  // ufix1
  input   i_level_send;  // ufix1
  input   [31:0] i_send_data;  // ufix32
  input   [13:0] i_send_address;  // ufix14
  output  o_receive_pulse;  // ufix1
  output  o_level_receive;  // ufix1
  (* cdc_info  = "max_delay_endpoint_axi_to_ip", dont_touch  = "true" *)     output [31:0] o_receive_data;  // ufix32
  (* cdc_info  = "max_delay_endpoint_axi_to_ip", dont_touch  = "true" *)     output [13:0] o_receive_address;  // ufix14


  wire enb;
  wire const_1;  // ufix1
  (* cdc_info  = "synchronizer_false_path", dont_touch  = "true" *)   reg s_level_2FlopSync_1;  // ufix1
  (* cdc_info  = "max_delay_clk_axi_to_ip", dont_touch  = "true" *)   reg s_level_2FlopSync_2;  // ufix1
  reg  s_level_2FlopSync_delayed;  // ufix1
  wire s_receive_pulse;  // ufix1
  reg  o_receive_pulse_1;  // ufix1
  (* cdc_info  = "max_delay_endpoint_axi_to_ip", dont_touch  = "true" *)   reg [31:0] o_receive_data_1;  // ufix32
  (* cdc_info  = "max_delay_endpoint_axi_to_ip", dont_touch  = "true" *)   reg [13:0] o_receive_address_1;  // ufix14


  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge i_receive_clk)
    begin : reg_level_2FlopSync_1_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_1 <= i_level_send;
        end
      end
    end

  always @(posedge i_receive_clk)
    begin : reg_level_2FlopSync_2_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_2 <= s_level_2FlopSync_1;
        end
      end
    end

  always @(posedge i_receive_clk)
    begin : reg_rsvd_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_delayed <= s_level_2FlopSync_2;
        end
      end
    end

  assign s_receive_pulse = s_level_2FlopSync_2 ^ s_level_2FlopSync_delayed;

  always @(posedge i_receive_clk)
    begin : reg_rsvd_1_process
      if (i_receive_rst == 1'b1) begin
        o_receive_pulse_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          o_receive_pulse_1 <= s_receive_pulse;
        end
      end
    end

  assign o_level_receive = s_level_2FlopSync_delayed;

  always @(posedge i_receive_clk)
    begin : reg_receive_wdata_process
      if (i_receive_rst == 1'b1) begin
        o_receive_data_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && s_receive_pulse) begin
          o_receive_data_1 <= i_send_data;
        end
      end
    end

  always @(posedge i_receive_clk)
    begin : reg_receive_waddress_process
      if (i_receive_rst == 1'b1) begin
        o_receive_address_1 <= 14'b00000000000000;
      end
      else begin
        if (enb && s_receive_pulse) begin
          o_receive_address_1 <= i_send_address;
        end
      end
    end

  assign o_receive_pulse = o_receive_pulse_1;

  assign o_receive_data = o_receive_data_1;

  assign o_receive_address = o_receive_address_1;

endmodule  // dvfs_core_ip_write_sync_receive_clk

