// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_zed_simple.v
// Created: 2025-11-19 14:16:11
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_zed_simple
// Source Path: dvfs_zed_simple
// Hierarchy Level: 0
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_zed_simple;




  // All logic inside the DUT 'dvfs_zed_simple' was detected to be redundant by HDL Coder. Consider connecting output 
  // ports to the design in order to preserve logic for code generation


endmodule  // dvfs_zed_simple

