// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_addr_decoder_read_registers.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_addr_decoder_read_registers
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_addr_decoder/dvfs_core_ip_addr_decoder_read/dvfs_core_ip_addr_decoder_read_registers
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_addr_decoder_read_registers
          (IPCORE_CLK,
           IPCORE_RESET,
           rd_enb_latch,
           read_ip_timestamp,
           read_p_state,
           read_W_log_strobe,
           read_W_log,
           read_ip_timestamp_sync,
           read_p_state_sync,
           read_W_log_sync);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESET;  // ufix1
  input   rd_enb_latch;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   [7:0] read_p_state;  // ufix8
  input   read_W_log_strobe;  // ufix1
  input   [63:0] read_W_log;  // ufix64
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output [31:0] read_ip_timestamp_sync;  // ufix32
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output [7:0] read_p_state_sync;  // ufix8
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)     output [63:0] read_W_log_sync;  // ufix64


  wire enb;
  wire const_1;  // ufix1
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)   reg [31:0] s_read_ip_timestamp_toAXI;  // ufix32
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)   reg [7:0] s_read_p_state_toAXI;  // ufix8
  (* cdc_info  = "max_delay_startpoint_ip_to_axi", dont_touch  = "true" *)   reg [63:0] s_read_W_log_toAXI;  // ufix64


  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge IPCORE_CLK)
    begin : reg_ip_timestamp_process
      if (IPCORE_RESET == 1'b1) begin
        s_read_ip_timestamp_toAXI <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && rd_enb_latch) begin
          s_read_ip_timestamp_toAXI <= read_ip_timestamp;
        end
      end
    end

  assign read_ip_timestamp_sync = s_read_ip_timestamp_toAXI;

  always @(posedge IPCORE_CLK)
    begin : reg_p_state_process
      if (IPCORE_RESET == 1'b1) begin
        s_read_p_state_toAXI <= 8'b00000000;
      end
      else begin
        if (enb && rd_enb_latch) begin
          s_read_p_state_toAXI <= read_p_state;
        end
      end
    end

  assign read_p_state_sync = s_read_p_state_toAXI;

  always @(posedge IPCORE_CLK)
    begin : reg_W_log_process
      if (IPCORE_RESET == 1'b1) begin
        s_read_W_log_toAXI <= 64'h0000000000000000;
      end
      else begin
        if (enb && read_W_log_strobe) begin
          s_read_W_log_toAXI <= read_W_log;
        end
      end
    end

  assign read_W_log_sync = s_read_W_log_toAXI;

endmodule  // dvfs_core_ip_addr_decoder_read_registers

