-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_zed_simple.vhd
-- Created: 2025-11-19 14:15:20
-- 
-- Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dvfs_zed_simple
-- Source Path: dvfs_zed_simple
-- Hierarchy Level: 0
-- Model version: 1.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dvfs_zed_simple IS
END dvfs_zed_simple;


ARCHITECTURE rtl OF dvfs_zed_simple IS

BEGIN
  -- All logic inside the DUT 'dvfs_zed_simple' was detected to be redundant by HDL Coder. Consider connecting output 
  -- ports to the design in order to preserve logic for code generation

END rtl;

