// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_src_nfp_relop_single.v
// Created: 2025-11-20 11:40:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_src_nfp_relop_single
// Source Path: dvfs_zed_simple/dvfs_core_hdl/LMS_predictor/nfp_relop_single
// Hierarchy Level: 2
// Model version: 1.7
// 
// {Latency Strategy = "Max"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_src_nfp_relop_single
          (clk,
           reset,
           enb,
           nfp_in1,
           nfp_in2,
           nfp_out1);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] nfp_in1;  // ufix32
  input   [31:0] nfp_in2;  // ufix32
  output  nfp_out1;  // ufix1


  wire Constant8_out1;  // ufix1
  wire [2:0] Constant7_out1;  // ufix3
  wire Relational_Operator_out1;
  reg  Delay13_out1;
  wire Logical_Operator2_out1;
  wire Logical_Operator_out1;  // ufix1
  wire [2:0] Add_out1;  // ufix3
  reg [2:0] Delay12_out1;  // ufix3
  wire [2:0] Add_1;  // ufix3
  wire Logical_Operator2_out1_1;
  wire AS;  // ufix1
  wire [7:0] AE;  // ufix8
  wire [22:0] AM;  // ufix23
  reg [7:0] Delay2_out1;  // uint8
  wire [7:0] Constant2_out1;  // uint8
  wire Relational_Operator5_out1;
  reg  Delay5_out1;
  wire [22:0] Constant1_out1;  // ufix23
  reg [22:0] Delay3_out1;  // ufix23
  wire Relational_Operator4_out1;
  reg  Delay3_out1_1;
  wire BS;  // ufix1
  wire [7:0] BE;  // ufix8
  wire [22:0] BM;  // ufix23
  reg [7:0] Delay4_out1;  // uint8
  wire Relational_Operator6_out1;
  reg  Delay6_out1;
  reg [22:0] Delay5_out1_1;  // ufix23
  wire Relational_Operator2_out1;
  reg  Delay2_out1_1;
  wire Logical_Operator4_out1;
  wire Logical_Operator1_out1;
  wire Logical_Operator5_out1;
  wire Logical_Operator2_out1_2;
  wire Logical_Operator3_out1;
  wire [7:0] Constant_out1;  // uint8
  wire Relational_Operator3_out1;
  reg  Delay1_out1;
  wire Relational_Operator1_out1;
  reg  Delay4_out1_1;
  wire Logical_Operator_out1_1;
  reg  Delay_out1;  // ufix1
  reg  Delay1_out1_1;  // ufix1
  wire Relational_Operator2_out1_1;
  reg  Delay3_out1_2;
  wire Relational_Operator4_out1_1;
  reg  Delay5_out1_2;
  wire Relational_Operator6_out1_1;
  reg  Delay7_out1;
  wire Relational_Operator5_out1_1;
  reg  Delay6_out1_1;
  wire Compare_To_Constant_out1;
  reg  Delay2_out1_2;
  wire Logical_Operator3_out1_1;
  wire switch_compare_1;
  wire Relational_Operator1_out1_1;
  reg  Delay4_out1_2;
  wire Relational_Operator3_out1_1;
  reg  Delay1_out1_2;
  wire Logical_Operator1_out1_1;
  wire Logical_Operator2_out1_3;
  wire Logical_Operator7_out1;
  wire Logical_Operator5_out1_1;
  wire Logical_Operator6_out1;
  wire Logical_Operator4_out1_1;
  wire Switch_out1;
  wire Logical_Operator4_out1_2;
  wire Logical_Operator3_out1_2;
  reg  Delay1_out1_3;
  wire Logical_Operator1_out1_2;
  reg  Delay10_out1;
  wire Logical_Operator4_out1_3;
  wire Constant1_out1_1;
  wire Switch4_out1;


  assign Constant8_out1 = 1'b1;

  assign Constant7_out1 = 3'b011;

  always @(posedge clk)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay13_out1 <= Relational_Operator_out1;
        end
      end
    end

  assign Logical_Operator2_out1 =  ~ Delay13_out1;

  assign Logical_Operator_out1 = Constant8_out1 & Logical_Operator2_out1;

  always @(posedge clk)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 3'b000;
      end
      else begin
        if (enb) begin
          Delay12_out1 <= Add_out1;
        end
      end
    end

  assign Add_1 = {2'b0, Logical_Operator_out1};
  assign Add_out1 = Delay12_out1 + Add_1;

  assign Relational_Operator_out1 = Add_out1 > Constant7_out1;

  assign Logical_Operator2_out1_1 =  ~ Relational_Operator_out1;

  // Split 32 bit word into FP sign, exponent, mantissa
  assign AS = nfp_in1[31];
  assign AE = nfp_in1[30:23];
  assign AM = nfp_in1[22:0];

  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= AE;
        end
      end
    end

  assign Constant2_out1 = 8'b11111111;

  assign Relational_Operator5_out1 = Delay2_out1 == Constant2_out1;

  always @(posedge clk)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Relational_Operator5_out1;
        end
      end
    end

  assign Constant1_out1 = 23'b00000000000000000000000;

  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= AM;
        end
      end
    end

  assign Relational_Operator4_out1 = Constant1_out1 == Delay3_out1;

  always @(posedge clk)
    begin : Delay3_1_process
      if (reset == 1'b1) begin
        Delay3_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1_1 <= Relational_Operator4_out1;
        end
      end
    end

  // Split 32 bit word into FP sign, exponent, mantissa
  assign BS = nfp_in2[31];
  assign BE = nfp_in2[30:23];
  assign BM = nfp_in2[22:0];

  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= BE;
        end
      end
    end

  assign Relational_Operator6_out1 = Delay4_out1 == Constant2_out1;

  always @(posedge clk)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= Relational_Operator6_out1;
        end
      end
    end

  always @(posedge clk)
    begin : Delay5_1_process
      if (reset == 1'b1) begin
        Delay5_out1_1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1_1 <= BM;
        end
      end
    end

  assign Relational_Operator2_out1 = Constant1_out1 == Delay5_out1_1;

  always @(posedge clk)
    begin : Delay2_1_process
      if (reset == 1'b1) begin
        Delay2_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay2_out1_1 <= Relational_Operator2_out1;
        end
      end
    end

  assign Logical_Operator4_out1 =  ~ Delay3_out1_1;

  assign Logical_Operator1_out1 = Delay5_out1 & Logical_Operator4_out1;

  assign Logical_Operator5_out1 =  ~ Delay2_out1_1;

  assign Logical_Operator2_out1_2 = Delay6_out1 & Logical_Operator5_out1;

  assign Logical_Operator3_out1 = Logical_Operator1_out1 | Logical_Operator2_out1_2;

  assign Constant_out1 = 8'b00000000;

  assign Relational_Operator3_out1 = Constant_out1 == Delay4_out1;

  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Relational_Operator3_out1;
        end
      end
    end

  assign Relational_Operator1_out1 = Constant_out1 == Delay2_out1;

  always @(posedge clk)
    begin : Delay4_1_process
      if (reset == 1'b1) begin
        Delay4_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_out1_1 <= Relational_Operator1_out1;
        end
      end
    end

  assign Logical_Operator_out1_1 = Delay3_out1_1 & (Delay4_out1_1 & (Delay2_out1_1 & Delay1_out1));

  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= AS;
        end
      end
    end

  always @(posedge clk)
    begin : Delay1_1_process
      if (reset == 1'b1) begin
        Delay1_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_1 <= BS;
        end
      end
    end

  assign Relational_Operator2_out1_1 = Delay_out1 == Delay1_out1_1;

  always @(posedge clk)
    begin : Delay3_2_process
      if (reset == 1'b1) begin
        Delay3_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1_2 <= Relational_Operator2_out1_1;
        end
      end
    end

  assign Relational_Operator4_out1_1 = Delay2_out1 == Delay4_out1;

  always @(posedge clk)
    begin : Delay5_2_process
      if (reset == 1'b1) begin
        Delay5_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay5_out1_2 <= Relational_Operator4_out1_1;
        end
      end
    end

  assign Relational_Operator6_out1_1 = Delay3_out1 == Delay5_out1_1;

  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Relational_Operator6_out1_1;
        end
      end
    end

  assign Relational_Operator5_out1_1 = Delay_out1 < Delay1_out1_1;

  always @(posedge clk)
    begin : Delay6_1_process
      if (reset == 1'b1) begin
        Delay6_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay6_out1_1 <= Relational_Operator5_out1_1;
        end
      end
    end

  assign Compare_To_Constant_out1 = Delay1_out1_1 == 1'b1;

  always @(posedge clk)
    begin : Delay2_2_process
      if (reset == 1'b1) begin
        Delay2_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay2_out1_2 <= Compare_To_Constant_out1;
        end
      end
    end

  assign Logical_Operator3_out1_1 = Delay2_out1_2 & Delay3_out1_2;

  assign switch_compare_1 = Logical_Operator3_out1_1 > 1'b0;

  assign Relational_Operator1_out1_1 = Delay2_out1 > Delay4_out1;

  always @(posedge clk)
    begin : Delay4_2_process
      if (reset == 1'b1) begin
        Delay4_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_out1_2 <= Relational_Operator1_out1_1;
        end
      end
    end

  assign Relational_Operator3_out1_1 = Delay3_out1 > Delay5_out1_1;

  always @(posedge clk)
    begin : Delay1_2_process
      if (reset == 1'b1) begin
        Delay1_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_2 <= Relational_Operator3_out1_1;
        end
      end
    end

  assign Logical_Operator1_out1_1 = Delay5_out1_2 & Delay1_out1_2;

  assign Logical_Operator2_out1_3 = Delay4_out1_2 | Logical_Operator1_out1_1;

  assign Logical_Operator7_out1 = Delay3_out1_2 & Logical_Operator2_out1_3;

  assign Logical_Operator5_out1_1 =  ~ Logical_Operator7_out1;

  assign Logical_Operator6_out1 = Delay7_out1 & (Delay3_out1_2 & Delay5_out1_2);

  assign Logical_Operator4_out1_1 = Logical_Operator_out1_1 | Logical_Operator6_out1;

  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Logical_Operator7_out1 :
              Logical_Operator5_out1_1);

  assign Logical_Operator4_out1_2 = Delay6_out1_1 | Switch_out1;

  assign Logical_Operator3_out1_2 = Logical_Operator4_out1_1 | Logical_Operator4_out1_2;

  always @(posedge clk)
    begin : Delay1_3_process
      if (reset == 1'b1) begin
        Delay1_out1_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_3 <= Logical_Operator3_out1;
        end
      end
    end

  assign Logical_Operator1_out1_2 = Logical_Operator2_out1_1 | Delay1_out1_3;

  always @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= Logical_Operator3_out1_2;
        end
      end
    end

  assign Logical_Operator4_out1_3 =  ~ Delay10_out1;

  assign Constant1_out1_1 = 1'b0;

  assign Switch4_out1 = (Logical_Operator1_out1_2 == 1'b0 ? Logical_Operator4_out1_3 :
              Constant1_out1_1);

  assign nfp_out1 = Switch4_out1;

endmodule  // dvfs_core_ip_src_nfp_relop_single

