// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_src_LMS_predictor.v
// Created: 2025-11-20 11:40:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_src_LMS_predictor
// Source Path: dvfs_zed_simple/dvfs_core_hdl/LMS_predictor
// Hierarchy Level: 1
// Model version: 1.7
// 
// #codegen
// Cast input to single to avoid type mismatch
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_src_LMS_predictor
          (clk,
           reset,
           enb,
           u,
           y);


  input   clk;
  input   reset;
  input   enb;
  input   [63:0] u;  // double
  output  [31:0] y;  // single


  wire [31:0] kconst;  // ufix32
  wire [31:0] prev;  // ufix32
  wire [31:0] out0;  // ufix32
  wire [31:0] bias;  // ufix32
  wire [31:0] y_1;  // ufix32
  wire [31:0] const_rsvd;  // ufix32
  wire [31:0] const_rsvd_1;  // ufix32
  wire Out_1;
  reg [31:0] delayMatch_reg [0:2];  // ufix32 [3]
  reg [31:0] delayMatch_reg_next [0:2];  // ufix32 [3]
  reg [31:0] y_2;  // ufix32
  wire Out_1_1;
  wire [31:0] y_3;  // ufix32
  wire [31:0] out0_1;  // ufix32
  wire [31:0] y_4;  // ufix32
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_0_1;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32


  assign kconst = 32'h3f4ccccd;

  dvfs_core_ip_src_nfp_convert_double2single u_dvfs_zed_simple_dvfs_core_hdl_LMS_predictor_nfp_convert_double2single (.clk(clk),
                                                                                                                      .reset(reset),
                                                                                                                      .enb(enb),
                                                                                                                      .nfp_in(u),  // double
                                                                                                                      .nfp_out(prev)  // single
                                                                                                                      );

  // fixed weight
  // fixed bias
  // Prediction
  dvfs_core_ip_src_nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .nfp_in1(kconst),  // single
                                                  .nfp_in2(prev),  // single
                                                  .nfp_out(out0)  // single
                                                  );

  assign bias = 32'h3ca3d70a;

  dvfs_core_ip_src_nfp_add_single u_nfp_add_comp (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .nfp_in1(out0),  // single
                                                  .nfp_in2(bias),  // single
                                                  .nfp_out(y_1)  // single
                                                  );

  assign const_rsvd = 32'h00000000;

  assign const_rsvd_1 = 32'h3f800000;

  dvfs_core_ip_src_nfp_relop_single_block u_nfp_relop_comp (.clk(clk),
                                                            .reset(reset),
                                                            .enb(enb),
                                                            .nfp_in1(y_1),  // single
                                                            .nfp_in2(const_rsvd_1),  // single
                                                            .nfp_out1(Out_1)
                                                            );

  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd2; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg[delayMatch_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch_t_0_1 = 32'sd0; delayMatch_t_0_1 <= 32'sd2; delayMatch_t_0_1 = delayMatch_t_0_1 + 32'sd1) begin
            delayMatch_reg[delayMatch_t_0_1] <= delayMatch_reg_next[delayMatch_t_0_1];
          end
        end
      end
    end

  always @* begin
    y_2 = delayMatch_reg[2];
    delayMatch_reg_next[0] = y_1;

    for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd1; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
      delayMatch_reg_next[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg[delayMatch_t_0_0];
    end

  end

  dvfs_core_ip_src_nfp_relop_single u_nfp_relop_comp_1 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .nfp_in1(y_1),  // single
                                                        .nfp_in2(const_rsvd),  // single
                                                        .nfp_out1(Out_1_1)
                                                        );

  assign y_3 = 32'h3f800000;

  assign out0_1 = (Out_1 == 1'b0 ? y_2 :
              y_3);

  assign y_4 = 32'h00000000;

  // Clamp result
  assign y = (Out_1_1 == 1'b0 ? out0_1 :
              y_4);

endmodule  // dvfs_core_ip_src_LMS_predictor

