// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_pulse_sync.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_pulse_sync
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_pulse_sync
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_pulse_sync
          (i_send_clk,
           i_send_rst,
           i_receive_clk,
           i_receive_rst,
           i_send_pulse,
           o_receive_pulse,
           o_pulse_ack);


  input   i_send_clk;  // ufix1
  input   i_send_rst;  // ufix1
  input   i_receive_clk;  // ufix1
  input   i_receive_rst;  // ufix1
  input   i_send_pulse;  // ufix1
  output  o_receive_pulse;  // ufix1
  output  o_pulse_ack;  // ufix1


  wire enb;
  wire const_1;  // ufix1
  reg  s_send_pulse_delayed;  // ufix1
  reg  s_send_level;  // ufix1
  wire s_send_not_level;  // ufix1
  wire s_receive_feedback;  // ufix1
  (* cdc_info  = "synchronizer_false_path", dont_touch  = "true" *)   reg s_level_2FlopSync_1;  // ufix1
  reg  s_level_2FlopSync_2;  // ufix1
  reg  s_level_send_2FlopSync_delayed;  // ufix1


  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge i_send_clk)
    begin : reg_rsvd_process
      if (i_send_rst == 1'b1) begin
        s_send_pulse_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_send_pulse_delayed <= i_send_pulse;
        end
      end
    end

  assign s_send_not_level =  ~ s_send_level;

  always @(posedge i_send_clk)
    begin : reg_rsvd_1_process
      if (i_send_rst == 1'b1) begin
        s_send_level <= 1'b0;
      end
      else begin
        if (enb && s_send_pulse_delayed) begin
          s_send_level <= s_send_not_level;
        end
      end
    end

  dvfs_core_ip_sync_receive_clk u_dvfs_core_ip_sync_receive_clk_inst (.i_receive_clk(i_receive_clk),  // ufix1
                                                                      .i_receive_rst(i_receive_rst),  // ufix1
                                                                      .i_level_send(s_send_level),  // ufix1
                                                                      .o_receive_pulse(o_receive_pulse),  // ufix1
                                                                      .o_receive_level(s_receive_feedback)  // ufix1
                                                                      );

  always @(posedge i_send_clk)
    begin : reg_level_2FlopSync_1_process
      if (i_send_rst == 1'b1) begin
        s_level_2FlopSync_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_1 <= s_receive_feedback;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : reg_level_2FlopSync_2_process
      if (i_send_rst == 1'b1) begin
        s_level_2FlopSync_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_2 <= s_level_2FlopSync_1;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : reg_rsvd_2_process
      if (i_send_rst == 1'b1) begin
        s_level_send_2FlopSync_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_send_2FlopSync_delayed <= s_level_2FlopSync_2;
        end
      end
    end

  assign o_pulse_ack = s_level_2FlopSync_2 ^ s_level_send_2FlopSync_delayed;

endmodule  // dvfs_core_ip_pulse_sync

