// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_src_dvfs_fsm.v
// Created: 2025-11-20 11:40:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_src_dvfs_fsm
// Source Path: dvfs_zed_simple/dvfs_core_hdl/dvfs_fsm
// Hierarchy Level: 1
// Model version: 1.7
// 
// 0=LOW, 1=MED, 2=HIGH
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_src_dvfs_fsm
          (clk,
           reset,
           enb,
           pred,
           p_state);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] pred;  // single
  output  [7:0] p_state;  // uint8


  wire stateControl_1;
  reg  [29:0] delayMatch1_reg;  // ufix1 [30]
  wire stateControl_2;
  wire intdelay_ctrl_const_out;
  reg  [30:0] delayMatch_reg;  // ufix1 [31]
  wire intdelay_ctrl_delay_out;
  wire [7:0] intdelay_Initial_Val_out;  // uint8
  wire [31:0] const_rsvd;  // ufix32
  wire Out_1;
  wire [7:0] desired;  // uint8
  wire [31:0] const_rsvd_2;  // ufix32
  wire Out_1_1;
  wire [31:0] const_rsvd_3;  // ufix32
  wire Out_1_2;
  wire [7:0] desired_1;  // uint8
  wire [7:0] desired_2;  // uint8
  wire [31:0] const_rsvd_4;  // ufix32
  wire Out_1_3;
  wire [7:0] desired_3;  // uint8
  wire [7:0] desired_4;  // uint8
  wire [7:0] out0;  // uint8
  wire [7:0] desired_5;  // uint8
  wire [7:0] desired_6;  // uint8
  wire out0_1;
  wire [7:0] out0_2;  // uint8
  wire out0_3;
  wire [7:0] out0_4;  // uint8
  reg [7:0] intdelay_out;  // uint8
  wire [7:0] desired_7;  // uint8
  reg [7:0] desired_last_value;  // uint8
  wire out0_5;
  wire [7:0] state;  // uint8
  wire out0_6;


  assign stateControl_1 = 1'b1;

  always @(posedge clk)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {30{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[32'sd29:32'sd1] <= delayMatch1_reg[32'sd28:32'sd0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[29];

  assign intdelay_ctrl_const_out = 1'b1;

  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {31{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= intdelay_ctrl_const_out;
          delayMatch_reg[32'sd30:32'sd1] <= delayMatch_reg[32'sd29:32'sd0];
        end
      end
    end

  assign intdelay_ctrl_delay_out = delayMatch_reg[30];

  assign intdelay_Initial_Val_out = 8'b00000001;

  assign const_rsvd = 32'h3e75c28f;

  dvfs_core_ip_src_nfp_relop_single u_nfp_relop_comp (.clk(clk),
                                                      .reset(reset),
                                                      .enb(enb),
                                                      .nfp_in1(pred),  // single
                                                      .nfp_in2(const_rsvd),  // single
                                                      .nfp_out1(Out_1)
                                                      );

  assign desired = 8'b00000001;

  assign const_rsvd_2 = 32'h3e8f5c29;

  dvfs_core_ip_src_nfp_relop_single_block1 u_nfp_relop_comp_1 (.clk(clk),
                                                               .reset(reset),
                                                               .enb(enb),
                                                               .nfp_in1(pred),  // single
                                                               .nfp_in2(const_rsvd_2),  // single
                                                               .nfp_out1(Out_1_1)
                                                               );

  assign const_rsvd_3 = 32'h3d75c28f;

  dvfs_core_ip_src_nfp_relop_single u_nfp_relop_comp_2 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .nfp_in1(pred),  // single
                                                        .nfp_in2(const_rsvd_3),  // single
                                                        .nfp_out1(Out_1_2)
                                                        );

  assign desired_1 = 8'b00000000;

  assign desired_2 = 8'b00000010;

  assign const_rsvd_4 = 32'h3dcccccd;

  dvfs_core_ip_src_nfp_relop_single_block1 u_nfp_relop_comp_3 (.clk(clk),
                                                               .reset(reset),
                                                               .enb(enb),
                                                               .nfp_in1(pred),  // single
                                                               .nfp_in2(const_rsvd_4),  // single
                                                               .nfp_out1(Out_1_3)
                                                               );

  // LOW
  assign desired_4 = (Out_1_3 == 1'b0 ? desired_3 :
              desired);

  assign out0 = (Out_1_2 == 1'b0 ? desired_3 :
              desired_1);

  // MED
  assign desired_5 = (Out_1_1 == 1'b0 ? out0 :
              desired_2);

  // HIGH
  assign desired_6 = (Out_1 == 1'b0 ? desired_3 :
              desired);

  assign out0_1 = desired_3 == 8'b00000010;

  assign out0_2 = (out0_1 == 1'b0 ? desired_3 :
              desired_6);

  assign out0_3 = desired_3 == 8'b00000001;

  assign out0_4 = (out0_3 == 1'b0 ? out0_2 :
              desired_5);

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_out <= 8'b00000000;
      end
      else begin
        if (enb) begin
          intdelay_out <= p_state;
        end
      end
    end

  assign desired_7 = (intdelay_ctrl_delay_out == 1'b0 ? intdelay_Initial_Val_out :
              intdelay_out);

  always @(posedge clk)
    begin : out0_bypass_process
      if (reset == 1'b1) begin
        desired_last_value <= 8'b00000000;
      end
      else begin
        if (enb) begin
          desired_last_value <= desired_3;
        end
      end
    end

  assign desired_3 = (stateControl_2 == 1'b0 ? desired_last_value :
              desired_7);

  assign out0_5 = desired_3 == 8'b00000000;

  assign state = (out0_5 == 1'b0 ? out0_4 :
              desired_4);

  assign out0_6 = state != desired_3;

  assign p_state = (out0_6 == 1'b0 ? desired_3 :
              state);

endmodule  // dvfs_core_ip_src_dvfs_fsm

