// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_axi_lite.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_axi_lite
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_axi_lite
          (AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           IPCORE_CLK,
           IPCORE_RESET,
           IPCORE_GLOBAL_RESET,
           read_ip_timestamp,
           read_p_state,
           read_W_log,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID,
           write_axi_enable,
           write_u,
           reset_internal);


  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESET;  // ufix1
  input   IPCORE_GLOBAL_RESET;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   [7:0] read_p_state;  // ufix8
  input   [63:0] read_W_log;  // ufix64
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1
  output  write_axi_enable;  // ufix1
  output  [63:0] write_u;  // ufix64
  output  reset_internal;  // ufix1


  wire reset;
  wire [31:0] top_data_write;  // ufix32
  wire [13:0] top_addr_write;  // ufix14
  wire top_wr_enb;  // ufix1
  wire [13:0] top_addr_read;  // ufix14
  wire top_rd_enb;  // ufix1
  wire [31:0] top_data_read;  // ufix32
  wire top_rd_enb_ack;  // ufix1
  wire top_reset_internal;  // ufix1
  wire top_reset_internal_sync;  // ufix1
  wire s_ack_pulse_reset;  // ufix1


  assign reset =  ~ AXI4_Lite_ARESETN;

  dvfs_core_ip_addr_decoder u_dvfs_core_ip_addr_decoder_inst (.data_write(top_data_write),  // ufix32
                                                              .addr_write(top_addr_write),  // ufix14
                                                              .wr_enb(top_wr_enb),  // ufix1
                                                              .addr_read(top_addr_read),  // ufix14
                                                              .rd_enb(top_rd_enb),  // ufix1
                                                              .IPCORE_CLK(IPCORE_CLK),  // ufix1
                                                              .IPCORE_RESET(IPCORE_RESET),  // ufix1
                                                              .IPCORE_GLOBAL_RESET(IPCORE_GLOBAL_RESET),  // ufix1
                                                              .AXI4_ACLK(AXI4_Lite_ACLK),
                                                              .AXI4_ARESET(reset),
                                                              .read_ip_timestamp(read_ip_timestamp),  // ufix32
                                                              .read_p_state(read_p_state),  // ufix8
                                                              .read_W_log(read_W_log),  // ufix64
                                                              .data_read(top_data_read),  // ufix32
                                                              .rd_enb_ack(top_rd_enb_ack),  // ufix1
                                                              .write_axi_enable(write_axi_enable),  // ufix1
                                                              .write_u(write_u)  // ufix64
                                                              );

  dvfs_core_ip_axi_lite_module u_dvfs_core_ip_axi_lite_module_inst (.clk(AXI4_Lite_ACLK),  // ufix1
                                                                    .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                                    .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                                    .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                                    .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                                    .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                                    .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                                    .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                                    .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                                    .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                                    .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                                    .data_read(top_data_read),  // ufix32
                                                                    .rd_enb_ack(top_rd_enb_ack),  // ufix1
                                                                    .IPCORE_CLK(IPCORE_CLK),  // ufix1
                                                                    .IPCORE_RESET(IPCORE_RESET),  // ufix1
                                                                    .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                                    .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                                    .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                                    .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                                    .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                                    .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                                    .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                                    .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                                    .data_write(top_data_write),  // ufix32
                                                                    .addr_write(top_addr_write),  // ufix14
                                                                    .wr_enb(top_wr_enb),  // ufix1
                                                                    .addr_read(top_addr_read),  // ufix14
                                                                    .rd_enb(top_rd_enb),  // ufix1
                                                                    .reset_internal(top_reset_internal)  // ufix1
                                                                    );

  dvfs_core_ip_pulse_sync u_dvfs_core_ip_soft_reset_sync_inst (.i_send_clk(AXI4_Lite_ACLK),  // ufix1
                                                               .i_send_rst(reset),
                                                               .i_receive_clk(IPCORE_CLK),  // ufix1
                                                               .i_receive_rst(IPCORE_RESET),  // ufix1
                                                               .i_send_pulse(top_reset_internal),  // ufix1
                                                               .o_receive_pulse(top_reset_internal_sync),  // ufix1
                                                               .o_pulse_ack(s_ack_pulse_reset)  // ufix1
                                                               );

  assign reset_internal = top_reset_internal_sync;

endmodule  // dvfs_core_ip_axi_lite

