// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_sync_receive_clk.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_sync_receive_clk
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_pulse_sync/dvfs_core_ip_sync_receive_clk
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_sync_receive_clk
          (i_receive_clk,
           i_receive_rst,
           i_level_send,
           o_receive_pulse,
           o_receive_level);


  input   i_receive_clk;  // ufix1
  input   i_receive_rst;  // ufix1
  input   i_level_send;  // ufix1
  output  o_receive_pulse;  // ufix1
  output  o_receive_level;  // ufix1


  wire enb;
  wire const_1;  // ufix1
  (* cdc_info  = "synchronizer_false_path", dont_touch  = "true" *)   reg s_level_2FlopSync1;  // ufix1
  reg  s_level_2FlopSync2;  // ufix1
  reg  s_level_2FlopSync_delayed;  // ufix1


  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge i_receive_clk)
    begin : reg_level_2FlopSync1_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync1 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync1 <= i_level_send;
        end
      end
    end

  always @(posedge i_receive_clk)
    begin : reg_level_2FlopSync2_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync2 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync2 <= s_level_2FlopSync1;
        end
      end
    end

  always @(posedge i_receive_clk)
    begin : reg_rsvd_process
      if (i_receive_rst == 1'b1) begin
        s_level_2FlopSync_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_delayed <= s_level_2FlopSync2;
        end
      end
    end

  assign o_receive_pulse = s_level_2FlopSync2 ^ s_level_2FlopSync_delayed;

  assign o_receive_level = s_level_2FlopSync_delayed;

endmodule  // dvfs_core_ip_sync_receive_clk

