// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_src_dvfs_core_hdl.v
// Created: 2025-11-20 11:40:08
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.1
// Target subsystem base rate: 0.1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// p_state                       ce_out        0.1
// W_log                         ce_out        0.1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_src_dvfs_core_hdl
// Source Path: dvfs_zed_simple/dvfs_core_hdl
// Hierarchy Level: 0
// Model version: 1.7
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_src_dvfs_core_hdl
          (clk,
           reset,
           clk_enable,
           u,
           ce_out,
           p_state,
           W_log);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [63:0] u;  // double
  output  ce_out;
  output  [7:0] p_state;  // uint8
  output  [63:0] W_log;  // double


  wire [31:0] y;  // ufix32
  wire [63:0] TmpGroundAtW_logInport1_out1;  // ufix64


  dvfs_core_ip_src_LMS_predictor u_LMS_predictor (.clk(clk),
                                                  .reset(reset),
                                                  .enb(clk_enable),
                                                  .u(u),  // double
                                                  .y(y)  // single
                                                  );

  dvfs_core_ip_src_dvfs_fsm u_dvfs_fsm (.clk(clk),
                                        .reset(reset),
                                        .enb(clk_enable),
                                        .pred(y),  // single
                                        .p_state(p_state)  // uint8
                                        );

  assign TmpGroundAtW_logInport1_out1 = 64'h0000000000000000;

  assign W_log = TmpGroundAtW_logInport1_out1;

  assign ce_out = clk_enable;

endmodule  // dvfs_core_ip_src_dvfs_core_hdl

