// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_write_data_sync.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_write_data_sync
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_axi_lite_module/dvfs_core_ip_write_data_sync
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_write_data_sync
          (i_send_clk,
           i_send_rst,
           i_receive_clk,
           i_receive_rst,
           i_send_pulse,
           i_send_data,
           i_send_address,
           o_send_data,
           o_send_pulse,
           o_receive_data,
           o_receive_address,
           o_decoder_enable,
           o_busy);


  input   i_send_clk;  // ufix1
  input   i_send_rst;  // ufix1
  input   i_receive_clk;  // ufix1
  input   i_receive_rst;  // ufix1
  input   i_send_pulse;  // ufix1
  input   [31:0] i_send_data;  // ufix32
  input   [13:0] i_send_address;  // ufix14
  (* cdc_info  = "max_delay_startpoint_axi_to_ip", dont_touch  = "true" *)     output [31:0] o_send_data;  // ufix32
  output  o_send_pulse;  // ufix1
  output  [31:0] o_receive_data;  // ufix32
  output  [13:0] o_receive_address;  // ufix14
  output  o_decoder_enable;  // ufix1
  output  o_busy;  // ufix1


  wire enb;
  wire const_1;  // ufix1
  (* cdc_info  = "max_delay_startpoint_axi_to_ip", dont_touch  = "true" *)   reg [31:0] o_send_data_1;  // ufix32
  reg  s_send_pulse_delayed;  // ufix1
  reg  s_send_level;  // ufix1
  wire s_send_not_level;  // ufix1
  (* cdc_info  = "max_delay_startpoint_axi_to_ip", dont_touch  = "true" *)   reg [13:0] s_send_waddr;  // ufix14
  wire s_level_receive;  // ufix1
  (* cdc_info  = "synchronizer_false_path", dont_touch  = "true" *)   reg s_level_2FlopSync_1;  // ufix1
  (* cdc_info  = "max_delay_clk_ip_to_axi", dont_touch  = "true" *)   reg s_level_2FlopSync_2;  // ufix1
  reg  s_level_send_2FlopSync_delayed;  // ufix1
  wire s_ack_pulse;  // ufix1
  reg  axi_lite_CDC_write_curr_state;  // ufix1
  reg  axi_lite_CDC_write_curr_state_next;  // ufix1
  reg  o_busy_1;  // ufix1


  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge i_send_clk)
    begin : reg_cdc_wdata_process
      if (i_send_rst == 1'b1) begin
        o_send_data_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && i_send_pulse) begin
          o_send_data_1 <= i_send_data;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : reg_rsvd_process
      if (i_send_rst == 1'b1) begin
        s_send_pulse_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_send_pulse_delayed <= i_send_pulse;
        end
      end
    end

  assign o_send_pulse = s_send_pulse_delayed;

  assign s_send_not_level =  ~ s_send_level;

  always @(posedge i_send_clk)
    begin : reg_rsvd_1_process
      if (i_send_rst == 1'b1) begin
        s_send_level <= 1'b0;
      end
      else begin
        if (enb && s_send_pulse_delayed) begin
          s_send_level <= s_send_not_level;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : reg_cdc_waddress_process
      if (i_send_rst == 1'b1) begin
        s_send_waddr <= 14'b00000000000000;
      end
      else begin
        if (enb && i_send_pulse) begin
          s_send_waddr <= i_send_address;
        end
      end
    end

  dvfs_core_ip_write_sync_receive_clk u_dvfs_core_ip_write_sync_receive_clk_inst (.i_receive_clk(i_receive_clk),  // ufix1
                                                                                  .i_receive_rst(i_receive_rst),  // ufix1
                                                                                  .i_level_send(s_send_level),  // ufix1
                                                                                  .i_send_data(o_send_data_1),  // ufix32
                                                                                  .i_send_address(s_send_waddr),  // ufix14
                                                                                  .o_receive_pulse(o_decoder_enable),  // ufix1
                                                                                  .o_level_receive(s_level_receive),  // ufix1
                                                                                  .o_receive_data(o_receive_data),  // ufix32
                                                                                  .o_receive_address(o_receive_address)  // ufix14
                                                                                  );

  always @(posedge i_send_clk)
    begin : reg_level_2FlopSync1_receive_process
      if (i_send_rst == 1'b1) begin
        s_level_2FlopSync_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_1 <= s_level_receive;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : reg_level_2FlopSync2_receive_process
      if (i_send_rst == 1'b1) begin
        s_level_2FlopSync_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_2FlopSync_2 <= s_level_2FlopSync_1;
        end
      end
    end

  always @(posedge i_send_clk)
    begin : intdelay_process
      if (i_send_rst == 1'b1) begin
        s_level_send_2FlopSync_delayed <= 1'b0;
      end
      else begin
        if (enb) begin
          s_level_send_2FlopSync_delayed <= s_level_2FlopSync_2;
        end
      end
    end

  assign s_ack_pulse = s_level_2FlopSync_2 ^ s_level_send_2FlopSync_delayed;

  always @(posedge i_send_clk)
    begin : axi_lite_CDC_write_process
      if (i_send_rst == 1'b1) begin
        axi_lite_CDC_write_curr_state <= 1'b0;
      end
      else begin
        if (enb) begin
          axi_lite_CDC_write_curr_state <= axi_lite_CDC_write_curr_state_next;
        end
      end
    end

  always @(axi_lite_CDC_write_curr_state, i_send_pulse, s_ack_pulse) begin
    axi_lite_CDC_write_curr_state_next = axi_lite_CDC_write_curr_state;
    case ( axi_lite_CDC_write_curr_state)
      1'b0 :
        begin
          o_busy_1 = 1'b0;
          if (i_send_pulse != 1'b0) begin
            axi_lite_CDC_write_curr_state_next = 1'b1;
          end
          else begin
            axi_lite_CDC_write_curr_state_next = 1'b0;
          end
        end
      1'b1 :
        begin
          o_busy_1 = 1'b1;
          if (s_ack_pulse != 1'b0) begin
            axi_lite_CDC_write_curr_state_next = 1'b0;
          end
          else begin
            axi_lite_CDC_write_curr_state_next = 1'b1;
          end
        end
      default :
        begin
          o_busy_1 = 1'b0;
        end
    endcase
  end

  assign o_send_data = o_send_data_1;

  assign o_busy = o_busy_1;

endmodule  // dvfs_core_ip_write_data_sync

