// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dvfs_zed_simple\dvfs_core_ip_addr_decoder.v
// Created: 2025-11-20 11:40:30
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvfs_core_ip_addr_decoder
// Source Path: dvfs_core_ip/dvfs_core_ip_axi_lite/dvfs_core_ip_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvfs_core_ip_addr_decoder
          (data_write,
           addr_write,
           wr_enb,
           addr_read,
           rd_enb,
           IPCORE_CLK,
           IPCORE_RESET,
           IPCORE_GLOBAL_RESET,
           AXI4_ACLK,
           AXI4_ARESET,
           read_ip_timestamp,
           read_p_state,
           read_W_log,
           data_read,
           rd_enb_ack,
           write_axi_enable,
           write_u);


  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_write;  // ufix14
  input   wr_enb;  // ufix1
  input   [13:0] addr_read;  // ufix14
  input   rd_enb;  // ufix1
  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESET;  // ufix1
  input   IPCORE_GLOBAL_RESET;  // ufix1
  input   AXI4_ACLK;
  input   AXI4_ARESET;
  input   [31:0] read_ip_timestamp;  // ufix32
  input   [7:0] read_p_state;  // ufix8
  input   [63:0] read_W_log;  // ufix64
  output  [31:0] data_read;  // ufix32
  output  rd_enb_ack;  // ufix1
  output  write_axi_enable;  // ufix1
  output  [63:0] write_u;  // ufix64


  wire read_axi_enable_sync;  // ufix1
  wire [63:0] read_u_sync;  // ufix64
  wire read_W_log_strobe;  // ufix1
  wire [31:0] s_data_read;  // ufix32


  dvfs_core_ip_addr_decoder_write u_dvfs_core_ip_addr_decoder_write_inst (.IPCORE_CLK(IPCORE_CLK),  // ufix1
                                                                          .IPCORE_GLOBAL_RESET(IPCORE_GLOBAL_RESET),  // ufix1
                                                                          .data_write(data_write),  // ufix32
                                                                          .addr_write(addr_write),  // ufix14
                                                                          .wr_enb(wr_enb),  // ufix1
                                                                          .read_axi_enable_sync(read_axi_enable_sync),  // ufix1
                                                                          .write_axi_enable(write_axi_enable),  // ufix1
                                                                          .read_u_sync(read_u_sync),  // ufix64
                                                                          .write_u(write_u),  // ufix64
                                                                          .read_W_log_strobe(read_W_log_strobe)  // ufix1
                                                                          );

  dvfs_core_ip_addr_decoder_read u_dvfs_core_ip_addr_decoder_read_inst (.IPCORE_CLK(IPCORE_CLK),  // ufix1
                                                                        .IPCORE_RESET(IPCORE_RESET),  // ufix1
                                                                        .AXI4_ACLK(AXI4_ACLK),
                                                                        .AXI4_ARESET(AXI4_ARESET),
                                                                        .addr_read(addr_read),  // ufix14
                                                                        .rd_enb(rd_enb),  // ufix1
                                                                        .read_axi_enable_sync(read_axi_enable_sync),  // ufix1
                                                                        .read_ip_timestamp(read_ip_timestamp),  // ufix32
                                                                        .read_u_sync(read_u_sync),  // ufix64
                                                                        .read_p_state(read_p_state),  // ufix8
                                                                        .read_W_log_strobe(read_W_log_strobe),  // ufix1
                                                                        .read_W_log(read_W_log),  // ufix64
                                                                        .rd_enb_ack(rd_enb_ack),  // ufix1
                                                                        .s_data_read(s_data_read)  // ufix32
                                                                        );

  assign data_read = s_data_read;

endmodule  // dvfs_core_ip_addr_decoder

